idme-shopping-cart/config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :items, only: [:show, :index]
  
  resource :cart, only: [:show] do
    put 'add/:id', to: 'carts#add', as: :add_to
    put 'remove/:id', to: 'carts#remove', as: :remove_from
  end

  root 'items#index'

end

idme-shopping-cart/app/models/item.rb
class Item < ActiveRecord::Base


	def infopage
	"http://www.colehaan.com/#{item_profile}"
	end

	def itemimage
		"http://demandware.edgesuite.net/#{item_image}"
	end

	def cart_action(current_user_id)
		if $redis.sismember "cart#{current_user_id}", id
			"Remove from"
		else
			"Add to"
		end
	end

end

idme-shopping-cart/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def cart_count
    $redis.scard "cart#{:item_id}"
  end
end

idme-shopping-cart/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception





end

idme-shopping-cart/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def show
    cart_ids = $redis.smembers current_user_cart
    @cart_items = Item.find(cart_ids)
  end

  def add
    $redis.sadd current_user_cart, params[:id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:id]
    render json: current_user.cart_count, status: 200
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

idme-shopping-cart/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @cart_action = @item.cart_action current_user.try :id
  end
end

idme-shopping-cart/app/helpers/application_helper.rb
module ApplicationHelper
end

idme-shopping-cart/app/helpers/carts_helper.rb
module CartsHelper
end

idme-shopping-cart/app/helpers/items_helper.rb
module ItemsHelper
end

idme-shopping-cart/app/views/carts/show.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>My Cart</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> items!</p>
  </div>
 
  <% @cart_items.each do |item|%>
  <div data-equalizer class="cart-item large-12 column mb1">
    <div class="column large-2 text-center p0" data-equalizer-watch>
      <%=link_to item do%>
        <%=image_tag item.itemimage, class: "radius-l1"%>
      <%end%>
    </div>
    <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
        <p class="scale ptm"> <%= item.title %> </p>
    </div>
    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
      <%=link_to "" , data: {targetUrl: remove_from_cart_path(item)} do%>
        <i class="fi-x right"></i>
      <%end%>
      <h4 class="scale">$ <%= item.price %></h4>
    </div>
  </div>
  <%end%>
</div>

idme-shopping-cart/app/views/items/index.html.erb
<h4 class="column">The Items</h4>
<div class="column">
  <ul class="items-grid no-bullet row">
    <% @items.each do |item| %>
      <li class="large-3 medium-4 small-12 column">
        <div class="item-card padly">
          <%= link_to item, class: "poster" do %>
            <%= image_tag item.itemimage %>
          <% end %>
          <div class="item-info ell glassy-bg padmy padlx">
            <div class="title">
              <h6><%= item.title %> </h6>
            </div>
            <p class="left price label radius">$ <%= item.price %></p>
            <%= link_to item.infopage, class: "right" do %>
              <%= image_tag asset_path("colehaan.jpg") %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

idme-shopping-cart/app/views/items/show.html.erb
<div class="large-3 small-12 column">
  <%=image_tag @item.itemimage%>
</div>
<div class="large-9 small-12 column">
  <h3>
    <%= @item.title %>
    <%=link_to @item.infopage do%>
      <%=image_tag asset_path("colehaan.jpg")%>
    <%end%>
  </h3>
  <p class="label item-label radius mb1">$ <%= @item.price %></p>

  <p><%= @item.description %></p>


  <%if signed_in?%>
    <%=link_to "Add to Cart", add_to_cart_path(@item), class: "button", method: :put %>

    <% # TODO: Fix this JavaScript issues: link_to "", class: "button", data: {target: @cart_action, addUrl: add_to_cart_path(@item), removeUrl: remove_from_cart_path(@item)} do%>
      <i class="fi-shopping-cart"></i>
      <span><%=@cart_action%></span> Cart
    <% # close do for javascript link %end%>
  <%end%>
</div>

idme-shopping-cart/app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

idme-shopping-cart/app/views/layouts/_header.html.erb
<div class="row">
  <nav class="top-bar column" data-topbar>

    <ul class="title-area">
      <li class="name">
        <h1>
          <a href="/">
            <i class="fi-play-video"></i> Kenn's Store
          </a>
        </h1>
      </li>
      <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">

      <!-- Right Nav Section -->
      <ul class="right">
        <%if signed_in?%>
          <li>
            <%= link_to cart_path do%>
              <i class="fi-shopping-cart"></i> My Cart (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
          </li>
          <li><%=link_to current_user.email, edit_user_registration_path%></li>
          <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
        <%else%>
          <li><%=link_to "Register", new_user_registration_path%></li>
          <li><%=link_to "Login", new_user_session_path%></li>
        <%end%>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li class="has-form">
          <div class="row collapse">
            <div class="large-8 small-9 columns">
              <input type="text" class="radius-ls expand" placeholder="Find Item">
            </div>
            <div class="large-4 small-3 columns">
              <a href="#" class=" radius-rs button">Search</a>
            </div>
          </div>
        </li>
      </ul>

    </section>

  </nav>
</div>

idme-shopping-cart/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Shoes- Let's get some Shoes!" %></title>
    <link rel="shortcut icon" href="<%=asset_path("logo.png")%>" >


    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/header"%>

    <%= render "layouts/alerts" %>

    <div id="main-content" class="row full-min-height">
      <%= yield %>
    </div>

    <footer class="row">
      <div class="large-12 columns">
        <hr>
        <p>© Kenn's Store 2015</p>
      </div>
    </footer>

    <%= javascript_include_tag "application" %>
    
  </body>
</html>